### ISSUE TITLE
Increase default display time to 30 seconds

### ISSUE THREAD

**Issue by chillibrie** [BricksMental/smirnybot9001#1]
Hello,

The current display time is too short.
Please increase it to 30 seconds as that duration has proven to be just right.

Thank you very much in advance.

**Comment by zxsdklfhskyrvk** [comment]
I fully agree on this.

**Comment by BricksMental** [comment]
Fixed in release v.0.0.3-alpha

**Comment by zxsdklfhskyrvk** [comment]
close this

**Comment by BricksMental** [comment]
Closing this, default is now 30s
