### ISSUE TITLE
Feature request: Part command

### ISSUE THREAD

**Issue by chillibrie** [BricksMental/smirnybot9001#2]
Hello,

Like the !set and !fig command, it would be nice to have a !part command.
This command could either be used only with the part number or the part colour code.

Example 1x1 plate 4073

Using part number
!part 4073
this would resolve to
https://www.bricklink.com/v2/catalog/catalogitem.page?P=4073

Using part colour code
!part 6351958
this would resolve to
https://www.bricklink.com/v2/catalog/catalogitem.page?P=4073&idColor=159

In a first step, the default command would be the most important one.
Sometimes, we only want to show what type of part we mean, regardless of the colour :)

This would really come in handy.
Thank you very much in advance.

**Comment by zxsdklfhskyrvk** [comment]
released?

**Comment by BricksMental** [comment]
Closing this. The !part command exists in the current release also with color support
