### ISSUE TITLE
Issue with IPv6 and slow bot performance

### ISSUE THREAD

**Issue by zxsdklfhskyrvk** [BricksMental/smirnybot9001#6]
On a Windows 10 system with default network config, there was an obvious 2 second delay for each of the loopback web requests (visible in the bots window).  I suspect something is not IPv6 enabled or compatible currently.

It appeared that (for each web request) IPv6 was attempted for 2 seconds and timing out, then IPv4 was attempted and immediately succeeded.

To fix the issue I set the following registry entry to Prefer IPv4 over IPv6 .  This requires a reboot but immediately addressed the issue.

This should not be necessary, and could lead to issues on various users systems.  Finding a way to make this work seamlessly on IPv6 is ideal.

https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/configure-ipv6-in-windows

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters\DisabledComponents
Decimal 32
Hexadecimal 0x20

**Comment by zxsdklfhskyrvk** [comment]
C:\Users\>D:\BricksMentalBot\Scripts\smirnyboot9001.exe -c D:\BricksMentalBot\legoinfobot.conf -w 1920 -h 1080 -p 37866
2022-10-20 18:23:07 INFO server.py Started httpserver http://:::37866/
2022-10-20 18:23:09 INFO websocket.py Successfully logged onto Twitch WS: legoinfobot
Logged in as | legoinfobot
User id is | 827305564
http://localhost:4711/part/number?value=4001
Error getting http://localhost:4711/part/number?value=4001: HTTPConnectionPool(host='localhost', port=4711): Max retries exceeded with url: /part/number?value=4001 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019E725C4580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
http://localhost:4711/part/duration?value=10
Error getting http://localhost:4711/part/duration?value=10: HTTPConnectionPool(host='localhost', port=4711): Max retries exceeded with url: /part/duration?value=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019E725C4CD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
http://localhost:4711/part/color?value=-99
Error getting http://localhost:4711/part/color?value=-99: HTTPConnectionPool(host='localhost', port=4711): Max retries exceeded with url: /part/color?value=-99 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019E725C5450>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
http://localhost:4711/part/display
Error getting http://localhost:4711/part/display: HTTPConnectionPool(host='localhost', port=4711): Max retries exceeded with url: /part/display (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000019E725C4BE0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

**Comment by user23498723452** [comment]
I need to doublecheck the performance on this.

**Comment by zxsdklfhskyrvk** [comment]
This is confirmed as fixed. It responds quickly now,  as opposed to the previous 2 sec delay.
